---
title: "flatpak"
date: "12/28/2024"
categories: [ "Package Management" ]
---
## Installing Flatpak

Before you can use Flatpak, you'll need to install it. The installation process varies slightly depending on your distribution, but the general steps are similar.  Here are instructions for some popular distributions:

**Fedora/Red Hat/CentOS:**

```bash
sudo dnf install flatpak
```

**Debian/Ubuntu:**

```bash
sudo apt install flatpak
```

**Arch Linux:**

```bash
sudo pacman -S flatpak
```

After installation, you might need to add the Flathub repository, the largest collection of Flatpak applications.  This is done using the following command:

```bash
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```


## Searching for Applications

Once Flatpak is installed and Flathub is added, you can search for applications.  Let's say you want to find a text editor:

```bash
flatpak search --remote flathub org.gnome.gedit
```

This will search the Flathub repository for applications containing "gedit" in their name or description.  You can replace `org.gnome.gedit` with any other application name or part of it.


## Installing Applications

Installing an application is straightforward.  Using the example of Gedit:

```bash
flatpak install flathub org.gnome.gedit
```

This command installs Gedit from the Flathub repository.  You can replace `org.gnome.gedit` with the application ID found during your search.  If you're installing multiple applications, just list their IDs separated by spaces.


## Updating Applications

Keeping your applications updated is important for security and stability. Flatpak makes this easy:

```bash
flatpak update
```

This command checks for updates for all your installed Flatpak applications and installs them.  You can also update individual applications:

```bash
flatpak update org.gnome.gedit
```


## Listing Installed Applications

To see a list of all your installed Flatpak applications:

```bash
flatpak list
```

This provides a concise overview of the installed applications, including their application ID and version.


## Uninstalling Applications

If you no longer need an application, you can uninstall it using:

```bash
flatpak uninstall org.gnome.gedit
```

Replace `org.gnome.gedit` with the application ID you want to remove.


## Managing Application Runtimes

Flatpak uses runtimes, which are sets of libraries and dependencies required by applications. You can list available runtimes with:

```bash
flatpak remote-ls flathub --app
```

And update runtimes individually or all of them:

```bash
flatpak update --runtime
flatpak update --system
```

These examples cover the essential commands for managing Flatpak applications.  With its sandboxed environment and simple commands, Flatpak offers a convenient and reliable way to manage software on your Linux system. Remember to replace example application IDs with those you find when searching for specific software.

