<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muthukrishnan">
<meta name="dcterms.date" content="2024-06-14">
<meta name="description" content="Explore Linux commands. Free knowledge sharing under MIT License.">

<title>fuser – Linux Commands Handbook</title>
<style>
html {
  color: #1a1a1a;
  background-color: #fdfdfd;
}
body {
  margin: 0 auto;
  max-width: 36em;
  padding-left: 50px;
  padding-right: 50px;
  padding-top: 50px;
  padding-bottom: 50px;
  hyphens: auto;
  overflow-wrap: break-word;
  text-rendering: optimizeLegibility;
  font-kerning: normal;
}
@media (max-width: 600px) {
  body {
    font-size: 0.9em;
    padding: 12px;
  }
  h1 {
    font-size: 1.8em;
  }
}
@media print {
  html {
    background-color: white;
  }
  body {
    background-color: transparent;
    color: black;
    font-size: 12pt;
  }
  p, h2, h3 {
    orphans: 3;
    widows: 3;
  }
  h2, h3, h4 {
    page-break-after: avoid;
  }
}
p {
  margin: 1em 0;
}
a {
  color: #1a1a1a;
}
a:visited {
  color: #1a1a1a;
}
img {
  max-width: 100%;
}
svg {
  height; auto;
  max-width: 100%;
}
h1, h2, h3, h4, h5, h6 {
  margin-top: 1.4em;
}
h5, h6 {
  font-size: 1em;
  font-style: italic;
}
h6 {
  font-weight: normal;
}
ol, ul {
  padding-left: 1.7em;
  margin-top: 1em;
}
li > ol, li > ul {
  margin-top: 0;
}
ul > li:not(:has(> p)) > ul,
ol > li:not(:has(> p)) > ul,
ul > li:not(:has(> p)) > ol,
ol > li:not(:has(> p)) > ol {
  margin-bottom: 0;
}
ul > li:not(:has(> p)) > ul > li:has(> p),
ol > li:not(:has(> p)) > ul > li:has(> p),
ul > li:not(:has(> p)) > ol > li:has(> p),
ol > li:not(:has(> p)) > ol > li:has(> p) {
  margin-top: 1rem;
}
blockquote {
  margin: 1em 0 1em 1.7em;
  padding-left: 1em;
  border-left: 2px solid #e6e6e6;
  color: #606060;
}
code {
  font-family: Menlo, Monaco, Consolas, 'Lucida Console', monospace;
  font-size: 85%;
  margin: 0;
  hyphens: manual;
}
pre {
  margin: 1em 0;
  overflow: auto;
}
pre code {
  padding: 0;
  overflow: visible;
  overflow-wrap: normal;
}
.sourceCode {
 background-color: transparent;
 overflow: visible;
}
hr {
  background-color: #1a1a1a;
  border: none;
  height: 1px;
  margin: 1em 0;
}
table {
  margin: 1em 0;
  border-collapse: collapse;
  width: 100%;
  overflow-x: auto;
  display: block;
  font-variant-numeric: lining-nums tabular-nums;
}
table caption {
  margin-bottom: 0.75em;
}
tbody {
  margin-top: 0.5em;
  border-top: 1px solid #1a1a1a;
  border-bottom: 1px solid #1a1a1a;
}
th {
  border-top: 1px solid #1a1a1a;
  padding: 0.25em 0.5em 0.25em 0.5em;
}
td {
  padding: 0.125em 0.5em 0.25em 0.5em;
}
header {
  margin-bottom: 4em;
  text-align: center;
}
#TOC li {
  list-style: none;
}
#TOC ul {
  padding-left: 1.3em;
}
#TOC > ul {
  padding-left: 0;
}
#TOC a:not(:hover) {
  text-decoration: none;
}
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<link href="../../../favicon.ico" rel="icon">
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-T5MFF1D7PZ"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-T5MFF1D7PZ', { 'anonymize_ip': true});
</script>
<link rel="icon" type="image/x-icon" href="../../../favicon.ico">
<meta property="og:title" content="fuser – Linux Commands Handbook">
<meta property="og:site_name" content="Linux Commands Handbook">
</head><body><div class="navigation-header">
    <nav>
        <div>
            <div class="logo">
                <a href="../../../" aria-label="Home">
                    <span>Linux Commands Handbook - Home</span>
                </a>
            </div>
            <div class="nav-menu">
                <ul>
                    <li>
                        <a href="../../../about.html">
                            <span class="menu-text">About</span>
                        </a>
                    </li>
                    <li> 
                        <a href="https://github.com/muthuspark" target="_blank">
                            <span class="menu-text">Github</span>
                        </a>
                    </li>
                    <li>
                        <a href="https://linkedin.com/in/krimuthu" target="_blank">
                            <span class="menu-text">Linkedin</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>


<link rel="stylesheet" href="../../../styles.css">





<header id="title-block-header">
<h1 class="title">fuser</h1>

<p class="date">2024-06-14</p>
</header>


<h2 id="understanding-fuser">Understanding <code>fuser</code></h2>
<p><code>fuser</code> is a command-line utility that displays the process IDs (PIDs) of processes currently using a specified file or socket. This is useful for troubleshooting resource conflicts, identifying processes blocking file operations, and generally improving your understanding of your system’s resource usage.</p>
<p>The basic syntax of <code>fuser</code> is straightforward:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fuser</span> <span class="pp">[</span><span class="ss">options</span><span class="pp">]</span> <span class="op">&lt;</span>file or socket<span class="op">&gt;</span></span></code></pre></div>
<p>Let’s look at its usage with practical examples.</p>
<h2 id="basic-usage-identifying-processes-using-a-file">Basic Usage: Identifying Processes Using a File</h2>
<p>Suppose you’re encountering issues with a file, <code>/var/log/my_app.log</code>, and suspect a process is holding it open, preventing modification or deletion. The simplest way to identify the culprit is:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fuser</span> /var/log/my_app.log</span></code></pre></div>
<p>This command will return the PIDs of any processes using that file. If no processes are using the file, it will return nothing.</p>
<p><strong>Example Output:</strong></p>
<pre><code>/var/log/my_app.log:          12345 67890</code></pre>
<p>This output indicates that processes with PIDs 12345 and 67890 are currently accessing <code>/var/log/my_app.log</code>. You can then use this information to investigate those processes further using commands like <code>ps</code> or <code>top</code>.</p>
<h2 id="specifying-file-types-with-options">Specifying File Types with Options</h2>
<p><code>fuser</code> offers various options to refine your searches. The <code>-c</code> option helps filter by file type:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fuser</span> <span class="at">-c</span> /var/log/my_app.log</span></code></pre></div>
<p>This will only list processes that have the file open for writing (<code>c</code> stands for writing).</p>
<h2 id="working-with-sockets">Working with Sockets</h2>
<p><code>fuser</code> isn’t limited to files; it can also identify processes bound to specific sockets. To find processes using a socket, you simply specify the socket address:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fuser</span> <span class="at">-n</span> tcp 8080</span></code></pre></div>
<p>This will list processes using TCP port 8080. You can replace <code>tcp</code> with other socket families like <code>udp</code>.</p>
<p><strong>Example with <code>-k</code> option:</strong></p>
<p>The <code>-k</code> option allows you to kill the processes identified. However, caution is advised as this can have unintended consequences. <strong>Always understand the ramifications before using <code>-k</code>.</strong></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> fuser <span class="at">-k</span> <span class="at">-n</span> tcp 8080</span></code></pre></div>
<p>This command will attempt to kill all processes using TCP port 8080. The <code>sudo</code> is required as killing processes usually requires root privileges.</p>
<h2 id="handling-multiple-filessockets">Handling Multiple Files/Sockets</h2>
<p><code>fuser</code> allows you to check for multiple files simultaneously:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fuser</span> /var/log/my_app.log /etc/passwd</span></code></pre></div>
<p>This command will show PIDs of processes using either <code>/var/log/my_app.log</code> or <code>/etc/passwd</code>.</p>
<h2 id="advanced-usage-using--m-for-mounting-points">Advanced Usage: Using <code>-m</code> for Mounting Points</h2>
<p>The <code>-m</code> option is particularly useful when investigating processes interacting with entire mount points:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> fuser <span class="at">-m</span> /mnt/data</span></code></pre></div>
<p>This command lists processes using any file or directory within the <code>/mnt/data</code> mount point. <strong>Caution:</strong> This can produce a large amount of output.</p>
<h2 id="combining-options-for-powerful-searches">Combining Options for Powerful Searches</h2>
<p>The true power of <code>fuser</code> lies in combining options for specific and targeted queries. For example:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode bash"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sudo</span> fuser <span class="at">-kmc</span> /var/run/myservice.sock</span></code></pre></div>
<p>This command will attempt to kill all processes that have <code>/var/run/myservice.sock</code> open for writing.</p>
<p>These examples demonstrate the versatility and power of the <code>fuser</code> command in managing processes within a Linux environment. By effectively utilizing its options, you can efficiently diagnose and resolve issues related to file and socket usage, leading to a more stable system.</p>


<footer>
    <p>© 2024 · Content on this site is licensed under the <a href="https://opensource.org/licenses/MIT">MIT License</a> · Built with ♥</p>
</footer>
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3609399560636561" crossorigin="anonymous"></script>




</body></html>